# Generated by Django 4.0 on 2023-04-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='pasporte',
        ),
    ]
